# Numpy


In [1]:
import numpy as np

### Creating Array

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = np.array([1,2,'ABC',True])

In [6]:
b

array(['1', '2', 'ABC', 'True'], dtype='<U11')

## Properties Of Array

In [7]:
a1 = np.array([10,20,30,40])

In [8]:
a1

array([10, 20, 30, 40])

In [9]:
a1.ndim

1

In [11]:
a1.dtype

dtype('int32')

In [12]:
a1.shape

(4,)

In [13]:
a1.size

4

In [14]:
a1.itemsize

4

# Different way of Creating array

In [16]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [17]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
np.array(np.random.randn(5),dtype='int')

array([ 0,  0,  0, -1, -1])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.array([1,2,3,4],dtype='float')

array([1., 2., 3., 4.])

# Multidimensional array

In [26]:
np.array([[2,3],[3,4]])

array([[2, 3],
       [3, 4]])

In [27]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
np.arange(10,20).reshape(10)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
a = np.random.randn(24).reshape(2,3,4)

In [30]:
a

array([[[-1.86342524,  1.4920782 ,  0.56646745, -1.22340186],
        [ 0.77234421, -0.65341544, -1.04848504,  0.37876538],
        [-0.7928089 , -0.04496098, -1.27525786, -0.07731207]],

       [[ 0.04055956, -0.96695916,  0.00587335,  1.54321498],
        [ 0.11968996,  0.99763816,  0.11029082, -0.79086968],
        [-0.28299076,  1.00323147,  1.15247888,  0.36181245]]])

In [31]:
a.dtype

dtype('float64')

In [32]:
a.itemsize

8

In [33]:
a.size

24

In [34]:
a.shape

(2, 3, 4)

In [35]:
a.ndim

3

## Array Function

In [37]:
a = np.arange(10,20).reshape(2,5)

In [38]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
a.sum()

145

In [40]:
a.sum(axis=0)

array([25, 27, 29, 31, 33])

In [41]:
a.sum(axis=1)

array([60, 85])

In [43]:
a.max()

19

In [44]:
a.max(axis=1)

array([14, 19])

In [45]:
a.min()

10

In [46]:
a.min(axis=0)

array([10, 11, 12, 13, 14])

In [47]:
a.mean()

14.5

In [48]:
a.var()

8.25

In [49]:
a.std()

2.8722813232690143

# Numpy Function

In [51]:
a = np.array([1,2,2,2,2,2,3,3,3,4,4,4,4,5,5,5,7,7,7,8,8,9,9,9])

In [52]:
a

array([1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 7, 7, 7, 8, 8, 9,
       9, 9])

In [53]:
a.mean()

4.791666666666667

In [55]:
np.median(a)

4.0

In [56]:
np.mean(a)

4.791666666666667

In [58]:
q1 = np.quantile(a,0.25)

In [60]:
q3 = np.quantile(a,0.75)

In [61]:
iqr = q3 - q1

In [62]:
iqr

4.25

In [63]:
upper_range = q3 + 1.5*iqr

In [64]:
lower_range = q1 - 1.5*iqr

In [65]:
upper_range

13.375

In [66]:
lower_range


-3.625

# Math Function

In [67]:
np.sin(90)

0.8939966636005579

In [68]:
np.cos(90)

-0.4480736161291701

In [69]:
np.tan(90)

-1.995200412208242

In [70]:
np.log(10)

2.302585092994046

In [71]:
np.log(1)

0.0

In [72]:
np.log10(10)

1.0

In [74]:
np.log(np.log10(5))

-0.35814744992084513

In [75]:
np.sqrt(376)

19.390719429665317

# Reducing Skewness 

In [76]:
a = np.array([1,2,3,4,4,5,5,8,9,10,12,15,20,25,30])

In [77]:
a

array([ 1,  2,  3,  4,  4,  5,  5,  8,  9, 10, 12, 15, 20, 25, 30])

In [79]:
np.mean(a)

10.2

In [80]:
np.median(a)

8.0

In [81]:
from scipy.stats import skew

In [82]:
skew(a)

1.0544731510118297

In [83]:
a = np.sqrt(a)

In [84]:
a

array([1.        , 1.41421356, 1.73205081, 2.        , 2.        ,
       2.23606798, 2.23606798, 2.82842712, 3.        , 3.16227766,
       3.46410162, 3.87298335, 4.47213595, 5.        , 5.47722558])

In [85]:
skew(a)

0.4989605954872714

In [87]:
a1 = np.arange(10,16).reshape(3,2)

In [88]:
a2 = np.arange(16,22).reshape(3,2)

In [89]:
a1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [90]:
a2

array([[16, 17],
       [18, 19],
       [20, 21]])

In [92]:
np.concatenate([a1,a2])

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [93]:
np.concatenate([a1,a2],axis=1)

array([[10, 11, 16, 17],
       [12, 13, 18, 19],
       [14, 15, 20, 21]])

In [94]:
np.unique([1,1,2,2,3])

array([1, 2, 3])

In [95]:
np.unique([1,1,2,2,3],return_counts=True)

(array([1, 2, 3]), array([2, 2, 1], dtype=int64))

# Indexing and Slicing

In [96]:
a = np.arange(10,20).reshape(5,2)

In [97]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [98]:
a[1]

array([12, 13])

In [99]:
a[1][1]

13

In [100]:
a[1,1]

13

In [101]:
a[2:4,]

array([[14, 15],
       [16, 17]])

In [103]:
a[2:4,0:2]

array([[14, 15],
       [16, 17]])

In [104]:
a[2:4,1]

array([15, 17])

In [105]:
a[2,0]

14

In [106]:
a[3,1]

17

In [107]:
a[[0,2]]

array([[10, 11],
       [14, 15]])

In [108]:
a[[0,2],1]

array([11, 15])

In [109]:
a[[0,2],0]

array([10, 14])

# Boolean Indexing

In [110]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [111]:
a > 15

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [112]:
a[a > 15]

array([16, 17, 18, 19])

In [113]:
a % 2 == 0

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False]])

In [114]:
a[a % 2 == 0]

array([10, 12, 14, 16, 18])

In [116]:
a = np.array([1,2,3,4])

In [117]:
s = 10

In [118]:
a + s

array([11, 12, 13, 14])

In [119]:
a * s

array([10, 20, 30, 40])

# Broadcasting 

In [121]:
n1 = np.array([[1,2],[3,4]])

In [122]:
n2 = np.array([2,3])

In [125]:
n1

array([[1, 2],
       [3, 4]])

In [126]:
n2

array([2, 3])

In [127]:
n1 + n2

array([[3, 5],
       [5, 7]])

# Cross vs Dot Product

In [128]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [129]:
a1

array([[1, 2],
       [3, 4]])

In [130]:
a2

array([[5, 6],
       [7, 8]])

In [131]:
# Cross Product
a1 * a2

array([[ 5, 12],
       [21, 32]])

In [132]:
# Dot Product
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

# Finding Outliers

In [4]:
import numpy as np

In [2]:
def outlier(a):
    q1 = np.quantile(a,0.25)
    q3 = np.quantile(a,0.75)
    iqr = q3 - q1
    uw = q3 + 1.5*iqr
    lw = q1 - 1.5*iqr
    
    
    upper_outlier = a[ a > uw]
    lower_outlier = a[ a < lw]
    print(uw, lw)
    ot = np.concatenate([upper_outlier, lower_outlier])
    print(ot)
    return [i for i in a if i not in ot]

In [3]:
arr = np.array([100,500,-300,455,12,85,45,44])

In [4]:
outlier(arr)

417.875 -193.125
[ 500  455 -300]


[100, 12, 85, 45, 44]

In [90]:
def outlier(a):
    q1 = np.quantile(a,0.25)
    q3 = np.quantile(a,0.75)
    iqr = q3 - q1
    uw = q3 + 1.5*iqr
    lw = q1 - 1.5*iqr
    
    res = np.array([0])
    for i in a:
        if (i<uw and i>lw):
            
            return np.append(res,i)
    #ot = np.concatenate([upper_outlier, lower_outlier])
    #return [i for i in a if i not in ot]

In [91]:
arr = np.array([100,500,-300,455,12,85,45,44])

In [92]:
outlier(arr)

array([  0, 100])